/** Normalized English country / region labels → ISO 3166-1 alpha-2 (lowercase). Keep in sync with madura-web/src/lib/country-name-to-iso2.ts */

const ALIASES: Record<string, string> = {
  india: 'in',
  australia: 'au',
  'new zealand': 'nz',
  'united states': 'us',
  'united states of america': 'us',
  usa: 'us',
  america: 'us',
  canada: 'ca',
  mexico: 'mx',
  brazil: 'br',
  argentina: 'ar',
  chile: 'cl',
  peru: 'pe',
  colombia: 'co',
  'costa rica': 'cr',
  panama: 'pa',
  cuba: 'cu',
  jamaica: 'jm',
  bahamas: 'bs',
  barbados: 'bb',
  antigua: 'ag',
  'dominican republic': 'do',
  'puerto rico': 'pr',
  guatemala: 'gt',
  ecuador: 'ec',
  bolivia: 'bo',
  paraguay: 'py',
  uruguay: 'uy',
  venezuela: 've',
  'trinidad and tobago': 'tt',
  'united kingdom': 'gb',
  uk: 'gb',
  'great britain': 'gb',
  england: 'gb',
  scotland: 'gb',
  wales: 'gb',
  ireland: 'ie',
  france: 'fr',
  italy: 'it',
  spain: 'es',
  portugal: 'pt',
  germany: 'de',
  switzerland: 'ch',
  netherlands: 'nl',
  holland: 'nl',
  belgium: 'be',
  austria: 'at',
  greece: 'gr',
  hungary: 'hu',
  poland: 'pl',
  'czech republic': 'cz',
  czechia: 'cz',
  slovakia: 'sk',
  slovenia: 'si',
  croatia: 'hr',
  romania: 'ro',
  bulgaria: 'bg',
  serbia: 'rs',
  'bosnia and herzegovina': 'ba',
  montenegro: 'me',
  albania: 'al',
  'north macedonia': 'mk',
  macedonia: 'mk',
  estonia: 'ee',
  latvia: 'lv',
  lithuania: 'lt',
  finland: 'fi',
  sweden: 'se',
  norway: 'no',
  denmark: 'dk',
  iceland: 'is',
  malta: 'mt',
  cyprus: 'cy',
  luxembourg: 'lu',
  turkey: 'tr',
  türkiye: 'tr',
  russia: 'ru',
  ukraine: 'ua',
  georgia: 'ge',
  armenia: 'am',
  azerbaijan: 'az',
  egypt: 'eg',
  morocco: 'ma',
  tunisia: 'tn',
  algeria: 'dz',
  jordan: 'jo',
  israel: 'il',
  lebanon: 'lb',
  iran: 'ir',
  iraq: 'iq',
  oman: 'om',
  qatar: 'qa',
  kuwait: 'kw',
  bahrain: 'bh',
  'saudi arabia': 'sa',
  uae: 'ae',
  'united arab emirates': 'ae',
  dubai: 'ae',
  'abu dhabi': 'ae',
  'sri lanka': 'lk',
  nepal: 'np',
  bhutan: 'bt',
  bangladesh: 'bd',
  pakistan: 'pk',
  maldives: 'mv',
  mauritius: 'mu',
  seychelles: 'sc',
  madagascar: 'mg',
  'south africa': 'za',
  namibia: 'na',
  botswana: 'bw',
  zimbabwe: 'zw',
  zambia: 'zm',
  kenya: 'ke',
  tanzania: 'tz',
  uganda: 'ug',
  rwanda: 'rw',
  ethiopia: 'et',
  nigeria: 'ng',
  china: 'cn',
  japan: 'jp',
  'south korea': 'kr',
  korea: 'kr',
  thailand: 'th',
  vietnam: 'vn',
  cambodia: 'kh',
  laos: 'la',
  singapore: 'sg',
  malaysia: 'my',
  indonesia: 'id',
  philippines: 'ph',
  taiwan: 'tw',
  'hong kong': 'hk',
  macau: 'mo',
  mongolia: 'mn',
  kazakhstan: 'kz',
  uzbekistan: 'uz',
  fiji: 'fj',
  myanmar: 'mm',
  'new caledonia': 'nc',
};

function normalizeKey(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .replace(/\./g, '');
}

/**
 * Resolves a display string (country name, alias, or 2-letter code) to ISO alpha-2.
 */
export function resolveIso2FromCountryHint(hint: string | null | undefined): string | null {
  if (!hint) return null;
  const t = hint.trim();
  if (/^[a-z]{2}$/i.test(t)) return t.toLowerCase();
  const key = normalizeKey(t);
  return ALIASES[key] || null;
}
